### ISSUE TITLE
Visualization

### ISSUE THREAD

**Issue by sheshap** [wangzy22/P2P#3]
Hi,

Thank you for sharing the code.
Can you please provide instructions for the visualization results?

Thanks

**Comment by LavenderLA** [comment]
Hi, thanks for your interest in our work!

You can visualize the colorful projected image via the `img` tensor in this line: https://github.com/wangzy22/P2P/blob/13169a3029e0706b9de4d20b98662181699fc7d3/models/layers/encoder.py#L106

**Comment by auniquesun** [comment]
> Hi, thanks for your interest in our work!
> 
> You can visualize the colorful projected image via the `img` tensor in this line:
> 
> https://github.com/wangzy22/P2P/blob/13169a3029e0706b9de4d20b98662181699fc7d3/models/layers/encoder.py#L106

Hi, author!

I run the code you mentioned when testing with config `p2p_ConvNeXt-B-1k` on ModelNet40, and save all `img` in a batch (64 images) with opencv-python successfully, as the code shows. 
```
@staticmethod
def save_imgs(imgs):
        imgs = imgs.permute(0, 2, 3, 1)
        for i, img in enumerate(imgs):
            img = img.cpu().numpy()
            cv.imwrite(f'./img_{i}.png', img)
```

However, I found all saved images are just black background, an example is listed in the following 
![img_28](https://user-images.githubusercontent.com/25259958/195517139-a4208999-7a66-44c9-baee-5f6049fb48aa.png)

The results are obviously different from the images presented in the paper, what's the possible problem and can you give some insights or advice?

**Comment by LavenderLA** [comment]
Hi @auniquesun, thanks for your interest in our work!

We use `to_pil_image` function in `torchvision` to visualize our image. For example,
```
def vis_img(self, img):
    import torchvision.transforms.functional as tvF
    pic = tvF.to_pil_image(img)
    pic.save('vis_img.jpg')
```
Then you can use this function to visualize image:
```
img = self.img_layer(img_feat)  # B 3 224 224
self.vis_img(img[0].detach().cpu())
```

**Comment by auniquesun** [comment]
> 

Thank you, I got it.
